import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Intro-V3-App',
  description: 'Generated by create next app',
}

const links = [
  {href: '/', label: 'Home'},
  {href: '/docs', label: 'Todos'},
  {href: '/todos', label: 'Todos'}
]


export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <header>
        <nav>
          <ul className='flex items-center'>
            
          </ul>
        </nav>
      </header>
      <body className={inter.className}>{children}</body>
    </html>
  )
}
